laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



/*
|----------------------------------------------------------------------------
| Front End Routes
|----------------------------------------------------------------------------
*/

//Authentication Routes
Route::namespace('Auth')->group(function () {
    // Login Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');

    // Cart Login Routes
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');

    // Registration Routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    Route::get('reqreg', 'RegisterController@showRegRegForm')->name('reqreg');
    Route::post('reqreg', 'RegisterController@reqreg');

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm');
    Route::post('password/reset', 'ResetPasswordController@reset');
});

//Front-end Routes
Route::namespace('Front')->group(function () {
    //Navbar Routes
    Route::get('/', 'PagesController@index')->name('index');
    Route::post('/', 'BranchController@index')->name('branch');
    Route::get('/about', 'BranchController@about')->name('about');
    Route::post('/contact', 'BranchController@send')->name('contact');
    Route::get('/contact', 'BranchController@contact')->name('contact');
    Route::get('/reviews', 'OrganizationController@reviews')->name('oreviews');

    //Footer Routes
    Route::get('TNC','PagesController@TNC')->name('TNC');

    //Search bar
    Route::post('/search', 'SearchBarController@search')->name('search');
    Route::get('/search', 'SearchBarController@search')->name('search');
    Route::get('/{product_id}', 'InventoryItemController@show')->name('product.show');

    Route::resource('cart', 'CartController');

    //Login Required Routes
    Route::group(['middleware' => ['auth', 'web']], function () {
        // Shopping Cart Routes
        //Route::get("search", 'InventoryItemController@search')->name('search.product');
        
        Route::get('account', 'AccountController@index')->name('account');
        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');
        Route::get('checkout/success', 'CheckoutController@success')->name('checkout.success');
        Route::resource('customer.address', 'CustomerAddressController');
        Route::post("comment", 'InventoryItemController@addComment')->name('product.review');

        //Bank Transfer
        //Route::namespace('Payments')->group(function () {
            //Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            //Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
        //});

        //Route::namespace('Addresses')->group(function () {
            //Route::resource('country.state', 'CountryStateController');
            //Route::resource('state.city', 'StateCityController');
        //});
    });
});

    
    

/*
Route::namespace('Front')->group(function () {
    
    Route::get('/', 'PagesController@index')->name('index');

    Route::get('/about', 'BranchController@about')->name('about')->middleware('branch');

    Route::get('/contact', 'BranchController@contact')->name('contact');

    Route::post('/', 'BranchController@index');

    //Product
    // Search
    Route::post('/search', 'InventoryItemController@search');\
    // Show
    Route::get('/product', 'InventoryItemController@show');
});
*/

/*
|----------------------------------------------------------------------------
| Back End Hacks
|----------------------------------------------------------------------------
*/

Route::get('/refresh', function() {
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return redirect()->route('index');
});

laravel/app/Http/Controllers/Front/AccountController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AccountController extends Controller
{
    public function index()
    {
        return view('front.account')
            ->with('customer', auth()->user())
            ->with('orders', auth()->user()->transactions()->get())
            ->with('address', auth()->user()->address()->get());
    }
}

laravel/app/Http/Controllers/Front/BranchController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\View\Composers\BranchComposer;
use App\Branch;
use Illuminate\Support\Facades\View;
use App\Http\Middleware\BranchMiddleware;

class BranchController extends Controller
{
    public function index(Request $request)
    {
        session(['branch' => Branch::where('bid', $request->branch_id)->first()]);
        return view('front.index');
    }

    public function about()    
    {
        return view('front.about');
    }

    public function contact()    
    {
        return view('front.contact');
    }

    public function send(Request $request)
    {
        $request->session()->flash('message', "Thank you for contacting us. We will get back to you soon.");
        return view('front.contact');
    }

}

laravel/app/Http/Controllers/Front/CartController.php
<?php

namespace App\Http\Controllers\Front;

use App\Starbie\Carts\Requests\AddToCartRequest;
use App\Starbie\Carts\Repositories\Interfaces\CartRepositoryInterface;
use App\Starbie\InventoryItems\InventoryItem;
use App\Starbie\InventoryItems\Repositories\Interfaces\InventoryItemRepositoryInterface;
use App\Starbie\InventoryItems\Repositories\InventoryItemRepository;
use App\Starbie\InventoryItems\Transformations\InventoryItemTransformable;
use Gloudemans\Shoppingcart\CartItem;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CartController extends Controller
{
    use InventoryItemTransformable;

    /**
     * @var CartRepositoryInterface
     */
    private $cartRepo;

    /**
     * @var InventoryItemRepositoryInterface
     */
    private $productRepo;

    /**
     * @var CourierRepositoryInterface
     */
    private $courierRepo;

    /**
     * @var InventoryItemAttributeRepositoryInterface
     */
    private $productAttributeRepo;

    /**
     * CartController constructor.
     * @param CartRepositoryInterface $cartRepository
     * @param InventoryItemRepositoryInterface $productRepository
     * @param CourierRepositoryInterface $courierRepository
     * @param InventoryItemAttributeRepositoryInterface $productAttributeRepository
     */
    public function __construct(
        CartRepositoryInterface $cartRepository,
        InventoryItemRepositoryInterface $productRepository,
        CourierRepositoryInterface $courierRepository,
        InventoryItemAttributeRepositoryInterface $productAttributeRepository
    ) {
        $this->cartRepo = $cartRepository;
        $this->productRepo = $productRepository;
        $this->courierRepo = $courierRepository;
        $this->productAttributeRepo = $productAttributeRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courier = $this->courierRepo->findCourierById(request()->session()->get('courierId', 1));
        $shippingFee = $this->cartRepo->getShippingFee($courier);

        return view('front.carts.cart', [
            'cartItems' => $this->cartRepo->getCartItemsTransformed(),
            'subtotal' => $this->cartRepo->getSubTotal(),
            'tax' => $this->cartRepo->getTax(),
            'shippingFee' => $shippingFee,
            'total' => $this->cartRepo->getTotal(2, $shippingFee)
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  AddToCartRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddToCartRequest $request)
    {
        $product = $this->productRepo->findInventoryItemById($request->input('product'));

        if ($product->attributes()->count() > 0) {
            $productAttr = $product->attributes()->where('default', 1)->first();

            if (isset($productAttr->sale_price)) {
                $product->price = $productAttr->price;

                if (!is_null($productAttr->sale_price)) {
                    $product->price = $productAttr->sale_price;
                }
            }
        }

        $options = [];
        if ($request->has('productAttribute')) {

            $attr = $this->productAttributeRepo->findInventoryItemAttributeById($request->input('productAttribute'));
            $product->price = $attr->price;

            $options['product_attribute_id'] = $request->input('productAttribute');
            $options['combination'] = $attr->attributesValues->toArray();
        }

        $this->cartRepo->addToCart($product, $request->input('quantity'), $options);

        return redirect()->route('cart.index')
            ->with('message', 'Add to cart successful');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->cartRepo->updateQuantityInCart($id, $request->input('quantity'));

        request()->session()->flash('message', 'Update cart successful');
        return redirect()->route('cart.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->cartRepo->removeToCart($id);

        request()->session()->flash('message', 'Removed to cart successful');
        return redirect()->route('cart.index');
    }
}

laravel/app/Http/Controllers/Front/CategoryController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    //
}

laravel/app/Http/Controllers/Front/InventoryItemController.php
<?php

namespace App\Http\Controllers\Front;

use App\Starbie\InventoryItems\InventoryItem;
use App\Starbie\Categories\Category;
use App\Http\Controllers\Controller;
use App\Starbie\Organizations\Organization;
use Illuminate\Http\Request;
use App\Starbie\Reviews\Review;
use App\Starbie\Transactions\TransactionItem;
use App\Starbie\Transactions\Transaction;

class InventoryItemController extends Controller
{

    /**
     * 
     * @return Response
     */
    public function search(Request $request)    
    {
        $term = $request->get('term');
        $items = null;
        if ($term == '')
        {
            $term = '%';
        }
        $category = Category::where('name', 'LIKE', '%'.$term.'%')->first();
        $item = InventoryItem::where('name', 'LIKE', '%'.$term.'%')->first();
        if ($category != null)
        {
            $items = InventoryItem::where('catid', $category->catid)->get();
        }
        else if ($item != null)
        {
            $items = InventoryItem::where('catid', $item->catid)->get();
        }

        $organization = Organization::where('oid', env('ORGANIZATION_ID'))->first();
            
        return view('product.search', ['organization' => $organization, 'products' => $items]);

    }

    public function show($product_id)
    {    
        $item = InventoryItem::where('itemid', $product_id)->first();
        if ($item != null)
        {
            return view('product.show')->with('product', $item);
        }
        return view('front.index');
    }

    public function addComment(Request $request)
    {
        $review = new Review;
        $review->comment = $request->comment;
        $review->itemid = $request->itemid;
        $review->cid = auth()->user()->cid; 
        $transitem = TransactionItem::where('itemid', $review->itemid)->first();
        $error = FALSE;
        if ($transitem != NULL)
        {
            $tidquery = Transaction::where('cid', $review->cid)->where('tid', $transitem->tid)->first();
            if ($tidquery != NULL)
            {
                $review->tid = $tidquery->tid;
                $review->save();
            }
            else
            {
                $error = TRUE;
            }
        }
        else
        {
            $error = TRUE;
        }
        if ($error)
        {
            $request->session()->flash('error', "You must buy this item to be able to add a review.");
        }
        return redirect()->back();
    }

}

laravel/app/Http/Controllers/Front/OrganizationController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Starbie\Organizations\Organization;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use App\Http\View\Composers\OrganizationComposer;

class OrganizationController extends Controller
{
    public function reviews()    
    {
        return view('front.oreviews')->with('reviews', session('org')->oreviews()->get());
    }
}

laravel/app/Http/Controllers/Front/PagesController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Container;
use Illuminate\View\View;

class PagesController extends Controller
{

    public function index()    
    {
        return view('front.index');
    }

    public function TNC()
    {
        return view('front.TNC');
    }

}

laravel/app/Http/Controllers/Front/SearchBarController.php
<?php

namespace App\Http\Controllers\Front;

use App\Starbie\InventoryItems\InventoryItem;
use App\Starbie\Categories\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SearchBarController extends Controller
{

    /**
     * 
     * @return Response
     */
    public function search(Request $request)    
    {
        $term = $request->get('term');
        $items = null;
        if (strlen($term) == 0)
        {
            $term = '%';
        }
        $catid = $request->get("category_id");
        if ($catid != 0) {
            $category = Category::where('catid', $catid)->first();
        }
        else {
            $category = Category::where('name', 'LIKE', '%'.$term.'%')->first();
        }
        $item = InventoryItem::where('name', 'LIKE', '%'.$term.'%')->first();
        if ($category != null)
        {
            $items = InventoryItem::where('catid', $category->catid)->get();
        }
        else if ($item != null)
        {
            $items = InventoryItem::where('catid', $item->catid)->get();
        }
            
        return view('product.search')->with('products', $items);

    }

    public function show(Request $request)
    {    
        $item = InventoryItem::where('itemid', $request->input('id', false))->first();
        if ($item != null)
        {
            return view('product.show')->with('product', $item);
        }
        return view('front.home');
    }

}

laravel/resources/views/layouts/front/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-9325492-23"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', '{{ env('GOOGLE_ANALYTICS') }}');
    </script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name') }}</title>
    <title>Laracom - Laravel FREE E-Commerce Software</title>
    <meta name="description" content="Modern open-source e-commerce framework for free">
    <meta name="tags" content="modern, opensource, open-source, e-commerce, framework, free, laravel, php, php7, symfony, shop, shopping, responsive, fast, software, blade, cart, test driven, adminlte, storefront">
    <meta name="author" content="Jeff Simons Decena">
    <link href="{{ asset('css/style.min.css') }}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="{{ asset('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js')}}"></script>
    <script src="{{ asset('https://oss.maxcdn.com/respond/1.4.2/respond.min.js')}}"></script>
    <![endif]-->
    <link rel="apple-touch-icon" sizes="57x57" href="{{ asset('favicons/apple-icon-57x57.png')}}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ asset('favicons/apple-icon-60x60.png')}}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('favicons/apple-icon-72x72.png')}}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('favicons/apple-icon-76x76.png')}}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('favicons/apple-icon-114x114.png')}}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ asset('favicons/apple-icon-120x120.png')}}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ asset('favicons/apple-icon-144x144.png')}}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ asset('favicons/apple-icon-152x152.png')}}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('favicons/apple-icon-180x180.png')}}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{{ asset('favicons/android-icon-192x192.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicons/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ asset('favicons/favicon-96x96.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicons/favicon-16x16.png')}}">
    <link rel="manifest" href="{{ asset('favicons/manifest.json')}}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ asset('favicons/ms-icon-144x144.png')}}">
    <meta name="theme-color" content="#ffffff">
    @yield('css')
    <meta property="og:url" content="{{ request()->url() }}"/>
    @yield('og')
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js') }}"></script>
</head>
<body>
<noscript>
    <p class="alert alert-danger">
        You need to turn on your javascript. Some functionality will not work if this is disabled.
        <a href="https://www.enable-javascript.com/" target="_blank">Read more</a>
    </p>
</noscript>
<section>
    <div class="row hidden-xs">
        <div class="container">
            <div class="clearfix"></div>
            <div class="pull-right">
                <ul class="nav navbar-nav navbar-right">
                    @if(auth()->check())
                        <li><a href="{{ route('accounts', ['tab' => 'profile']) }}"><i class="fa fa-home"></i> My Account</a></li>
                        <li><a href="{{ route('logout') }}"><i class="fa fa-sign-out"></i> Logout</a></li>
                    @else
                        <li><a href="{{ route('login') }}"> <i class="fa fa-lock"></i> Login</a></li>
                        <li><a href="{{ route('register') }}"> <i class="fa fa-sign-in"></i> Register</a></li>
                    @endif
                    <li id="cart" class="menubar-cart">
                        <a href="{{ route('cart.index') }}" title="View Cart" class="awemenu-icon menu-shopping-cart">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            <span class="cart-number">{{ $cartCount }}</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <header id="header-section">
        <nav class="navbar navbar-default">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header col-md-2">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ route('home') }}">{{ config('app.name') }}</a>
                </div>
                <div class="col-md-10">
                    @include('layouts.front.header-cart')
                </div>
            </div>
        </nav>
    </header>
</section>
@yield('content')

@include('layouts.front.footer')

<script src="{{ asset('js/front.min.js') }}"></script>
<script src="{{ asset('js/custom.js') }}"></script>
@yield('js')
</body>
</html>

laravel/resources/views/layouts/front/category-nav.blade.php
<ul class="list-unstyled list-inline nav navbar-nav">
    @foreach($categories as $category)
        <li>
            @if($category->children()->count() > 0)
                @include('layouts.front.category-sub', ['subs' => $category->children])
            @else
                <a @if(request()->segment(2) == $category->slug) class="active" @endif href="{{route('front.category.slug', $category->slug)}}">{{$category->name}} </a>
            @endif
        </li>
    @endforeach
</ul>

laravel/resources/views/layouts/front/category-sidebar-sub.blade.php
@foreach($subs as $sub)
    <a href="{{ route('front.category.slug', $category->slug) }}">{{ $category->name }}</a>
    <ul class="list-unstyled sidebar-category-sub">
        <li @if(request()->segment(2) == $sub->slug) class="active" @endif ><a href="{{ route('front.category.slug', $sub->slug) }}">{{ $sub->name }}</a></li>
    </ul>
@endforeach

laravel/resources/views/layouts/front/category-sub.blade.php
<div class="dropdown">
    <a @if(request()->segment(2) == $category->slug) class="active" @endif href="{{route('front.category.slug', $category->slug)}}" class="dropdown-toggle" id="{{$category->slug}}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">{{$category->name}} <span class="caret"></span></a>
    <ul class="dropdown-menu" aria-labelledby="{{$category->slug}}">
        @foreach($subs as $sub)
            <li><a href="{{route('front.category.slug', $sub->slug)}}">{{$sub->name}}</a></li>
        @endforeach
    </ul>
</div>

laravel/resources/views/layouts/front/footer.blade.php
<footer class="footer-section footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">

                <ul class="footer-menu">
                    <li> <a href="{{ route('accounts', ['tab' => 'profile']) }}">Your account</a>  </li>
                    <li> <a href="">Contact us</a>  </li>
                    <li> <a href="">Terms of service</a>  </li>
                </ul>

                <ul class="footer-social">
                    <li> <a href=""> <i class="fa fa-facebook" aria-hidden="true"></i>  </a> </li>
                    <li> <a href=""> <i class="fa fa-twitter" aria-hidden="true"></i>   </a> </li>
                    <li> <a href=""> <i class="fa fa-instagram" aria-hidden="true"></i>  </a> </li>
                    <li> <a href=""> <i class="fa fa-pinterest-p" aria-hidden="true"></i>  </a> </li>
                </ul>

                <p>&copy; <a href="{{ config('app.url') }}">{{ config('app.name') }}</a> | All Rights Reserved</p>

            </div>
        </div>
    </div>
</footer>

laravel/resources/views/layouts/front/header-cart.blade.php
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    @include('layouts.front.category-nav')
    <ul class="nav navbar-nav navbar-right">
        @if(auth()->check())
            <li class="visible-xs"><a href="{{ route('accounts', ['tab' => 'profile']) }}"><i class="fa fa-home"></i> My Account</a></li>
            <li class="visible-xs"><a href="{{ route('logout') }}"><i class="fa fa-sign-out"></i> Logout</a></li>
        @else
            <li class="visible-xs"><a href="{{ route('login') }}"> <i class="fa fa-lock"></i> Login</a></li>
            <li class="visible-xs"><a href="{{ route('register') }}"> <i class="fa fa-sign-in"></i> Register</a></li>
        @endif
        <li id="cart" class="menubar-cart visible-xs">
            <a href="{{ route('cart.index') }}" title="View Cart" class="awemenu-icon menu-shopping-cart">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                <span class="cart-number">{{ $cartCount }}</span>
            </a>
        </li>
        <li>
            <!-- search form -->
            <form action="{{route('search.product')}}" method="GET" class="form-inline" style="margin: 15px 0 0;">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search..." value="{!! request()->input('q') !!}">
                    <span class="input-group-btn">
                        <button type="submit" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i> Search</button>
                    </span>
                </div>
            </form>
            <!-- /.search form -->
        </li>
    </ul>
</div><!-- /.navbar-collapse -->

laravel/resources/views/layouts/front/product.blade.php
<div class="row">
    <div class="col-md-6">
        <ul id="thumbnails" class="col-md-4 list-unstyled">
            <li>
                <a href="javascript: void(0)">
                    @if(isset($product->cover))
                    <img class="img-responsive img-thumbnail"
                         src="{{ asset("storage/$product->cover") }}"
                         alt="{{ $product->name }}" />
                    @else
                    <img class="img-responsive img-thumbnail"
                         src="{{ asset("https://placehold.it/180x180") }}"
                         alt="{{ $product->name }}" />
                    @endif
                </a>
            </li>
            @if(isset($images) && !$images->isEmpty())
                @foreach($images as $image)
                <li>
                    <a href="javascript: void(0)">
                    <img class="img-responsive img-thumbnail"
                         src="{{ asset("storage/$image->src") }}"
                         alt="{{ $product->name }}" />
                    </a>
                </li>
                @endforeach
            @endif
        </ul>
        <figure class="text-center product-cover-wrap col-md-8">
            @if(isset($product->cover))
                <img id="main-image" class="product-cover img-responsive"
                     src="{{ asset("storage/$product->cover") }}?w=400"
                     data-zoom="{{ asset("storage/$product->cover") }}?w=1200">
            @else
                <img id="main-image" class="product-cover" src="https://placehold.it/300x300"
                     data-zoom="{{ asset("storage/$product->cover") }}?w=1200" alt="{{ $product->name }}">
            @endif
        </figure>
    </div>
    <div class="col-md-6">
        <div class="product-description">
            <h1>{{ $product->name }}
                <small>{{ config('cart.currency') }} {{ $product->price }}</small>
            </h1>
            <div class="description">{!! $product->description !!}</div>
            <div class="excerpt">
                <hr>{!!  str_limit($product->description, 100, ' ...') !!}</div>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    @include('layouts.errors-and-messages')
                    <form action="{{ route('cart.store') }}" class="form-inline" method="post">
                        {{ csrf_field() }}
                        @if(isset($productAttributes) && !$productAttributes->isEmpty())
                            <div class="form-group">
                                <label for="productAttribute">Choose Combination</label> <br />
                                <select name="productAttribute" id="productAttribute" class="form-control select2">
                                    @foreach($productAttributes as $productAttribute)
                                        <option value="{{ $productAttribute->id }}">
                                            @foreach($productAttribute->attributesValues as $value)
                                                {{ $value->attribute->name }} : {{ ucwords($value->value) }}
                                            @endforeach
                                            @if(!is_null($productAttribute->price))
                                                ( {{ config('cart.currency_symbol') }} {{ $productAttribute->price }})
                                            @endif
                                        </option>
                                    @endforeach
                                </select>
                            </div><hr>
                        @endif
                        <div class="form-group">
                            <input type="text"
                                   class="form-control"
                                   name="quantity"
                                   id="quantity"
                                   placeholder="Quantity"
                                   value="{{ old('quantity') }}" />
                            <input type="hidden" name="product" value="{{ $product->id }}" />
                        </div>
                        <button type="submit" class="btn btn-warning"><i class="fa fa-cart-plus"></i> Add to cart
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@section('js')
    <script type="text/javascript">
        $(document).ready(function () {
            var productPane = document.querySelector('.product-cover');
            var paneContainer = document.querySelector('.product-cover-wrap');

            new Drift(productPane, {
                paneContainer: paneContainer,
                inlinePane: false
            });
        });
    </script>
@endsection